### ISSUE TITLE
Fatal error: Allowed memory size exhausted

### ISSUE THREAD

**Issue by nick-groupe-ratte** [TorqIT/store-syndicator-bundle#74]
Hello @evanjamesjackson @cameronfromtorq  On both the dev site and my local site I get an Allowed memory size exhausted error  for the getLocal?name=ShopifyExport call which means the local field dropdown doesnt have any options

**Comment by evanjamesjackson** [comment]
@nick-groupe-ratte Hi Nick, this has been fixed. Please pull down the latest version in your repo and let us know if it solved the problem.

**Comment by cameronfromtorq** [comment]
@nick-groupe-ratte sorry, forgot to create a release. You should be able to run `composer update torqit/store-syndicator-bundle` now and see if it fixes your issue.
