### ISSUE TITLE
Ability to limit which items are exported to Shopify

### ISSUE THREAD

**Issue by evanjamesjackson** [TorqIT/store-syndicator-bundle#78]
Via a filter, if possible

**Comment by evanjamesjackson** [comment]
@nick-groupe-ratte Hi Nick - sounds good, we will prioritize this in that case

**Comment by nick-groupe-ratte** [comment]
Hello @evanjamesjackson  Thank you, much appreciated

**Comment by evanjamesjackson** [comment]
@nick-groupe-ratte We have something implemented in a branch right now https://github.com/TorqIT/store-syndicator-bundle/tree/feat/export-deny-option (see README step 4). It's still a drag/drop but you would now be able to drag in items you want to exclude. Does this satisfy your requirement or were you thinking it should based off field value(s)?
