### ISSUE TITLE
Error at the end of export :  error during metafield setting in commit: cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to torqit-grouperatte-pimcore-test.myshopify.com:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://torqit-grouperatte-pimcore-test.myshopify.com/admin/api/2023-04/graphql.json File: /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php Line: 210

### ISSUE THREAD

**Issue by nick-groupe-ratte** [TorqIT/store-syndicator-bundle#81]
`root@7fe508ee4295:/var/www/html# bin/console torq:push-to-shopify "ShopifyExport"
start time: 1686056003
error during metafield setting in commit: cURL error 35: OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to torqit-grouperatte-pimcore-test.myshopify.com:443  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://torqit-grouperatte-pimcore-test.myshopify.com/admin/api/2023-04/graphql.json
File: /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php
Line: 210
Trace: #0 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(158): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(110): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(47): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\Handler\CurlHandler->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#4 /var/www/html/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(48): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#5 /var/www/html/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(64): GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#6 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(31): GuzzleHttp\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#7 /var/www/html/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(55): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#8 /var/www/html/vendor/guzzlehttp/guzzle/src/Middleware.php(61): GuzzleHttp\RedirectMiddleware->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#9 /var/www/html/vendor/guzzlehttp/guzzle/src/HandlerStack.php(75): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Request), Array)
#10 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(331): GuzzleHttp\HandlerStack->__invoke(Object(GuzzleHttp\Psr7\Request), Array)
#11 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(107): GuzzleHttp\Client->transfer(Object(GuzzleHttp\Psr7\Request), Array)
#12 /var/www/html/vendor/guzzlehttp/guzzle/src/Client.php(137): GuzzleHttp\Client->sendAsync(Object(GuzzleHttp\Psr7\Request), Array)
#13 /var/www/html/vendor/shopify/shopify-api/src/Clients/Http.php(195): GuzzleHttp\Client->sendRequest(Object(GuzzleHttp\Psr7\Request))
#14 /var/www/html/vendor/shopify/shopify-api/src/Clients/Http.php(74): Shopify\Clients\Http->request('admin/api/2023-...', 'POST', '{"query":"query...', Array, '', NULL, 'application/jso...')
#15 /var/www/html/vendor/shopify/shopify-api/src/Clients/Graphql.php(69): Shopify\Clients\Http->post('admin/api/2023-...', '{"query":"query...', Array, Array, NULL, 'application/jso...')
#16 /var/www/html/vendor/torqit/store-syndicator-bundle/src/Services/ShopifyHelpers/ShopifyQueryService.php(390): Shopify\Clients\Graphql->query('{"query":"query...')
#17 /var/www/html/vendor/torqit/store-syndicator-bundle/src/Services/ShopifyHelpers/ShopifyQueryService.php(248): TorqIT\StoreSyndicatorBundle\Services\ShopifyHelpers\ShopifyQueryService->queryFinished('MUTATION')
#18 /var/www/html/vendor/torqit/store-syndicator-bundle/src/Services/Stores/ShopifyStore.php(391): TorqIT\StoreSyndicatorBundle\Services\ShopifyHelpers\ShopifyQueryService->updateMetafields(Array)
#19 /var/www/html/vendor/torqit/store-syndicator-bundle/src/Services/ExecutionService.php(62): TorqIT\StoreSyndicatorBundle\Services\Stores\ShopifyStore->commit()
#20 /var/www/html/vendor/torqit/store-syndicator-bundle/src/Command/PushToShopifyCommand.php(39): TorqIT\StoreSyndicatorBundle\Services\ExecutionService->export(Object(Pimcore\Bundle\DataHubBundle\Configuration))
#21 /var/www/html/vendor/symfony/console/Command/Command.php(298): TorqIT\StoreSyndicatorBundle\Command\PushToShopifyCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(TorqIT\StoreSyndicatorBundle\Command\PushToShopifyCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(TorqIT\StoreSyndicatorBundle\Command\PushToShopifyCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/html/bin/console(49): Symfony\Component\Console\Application->run()
#28 {main}
products with over 100 variants: [129530,128886,127674,127640,127852,129368,128585,128663,128808,128513,129246,129275,129108,128801,128779,128955,127595,128584,128753,129507,128660,128040,127873,128110,129125,128128,128048,128800,128601,127955,127747,129461,127808,129367,384909,128290,128812]
final time: 1686070484
execution duration: 14481`

**Comment by evanjamesjackson** [comment]
@nick-groupe-ratte Hi Nick - is this a consistent error you're seeing or was it just a one-time thing? Also is anything failing to get pushed into Shopify or is this happening after everything finishes successfully?

**Comment by nick-groupe-ratte** [comment]
Hello @evanjamesjackson, since the process is very long I only ran it once and I was gonna wait until you guys have a look at the error message before trying again. Do you want me to try again?
I have not way of knowing if everything is sucessfully pushed into shopify as there are no logs.
