### ISSUE TITLE
Can't import Quantity

### ISSUE THREAD

**Issue by nick-groupe-ratte** [TorqIT/store-syndicator-bundle#82]
Hello, 
I just noticed that I can't import quantity. 
Shopify supports multiple locations but we only have one location per store and we only need to import the "available" quantity.
Would it be possible to allow us to map a calculated pimcore field to the quantity? We have 2 suppliers and we will store the quantity for each supplier separately in pimcore but we need them combined in shopify. I think the simplest way to do it is to use a calculated field.

**Comment by evanjamesjackson** [comment]
Moved to Linear
