### ISSUE TITLE
Error when running new Wheel exporter

### ISSUE THREAD

**Issue by nick-groupe-ratte** [TorqIT/store-syndicator-bundle#84]
I get the error 
```
In ShopifyQueryService.php line 40:
Warning: fopen(none): Failed to open stream: No such file or directory
```
[ShopifyExportWheels.yaml.txt](https://github.com/TorqIT/store-syndicator-bundle/files/11668482/ShopifyExportWheels.yaml.txt)

**Comment by cameronfromtorq** [comment]
@nick-groupe-ratte could you please give me a screenshot of your mapping tab or your config file that is resulting in this error?

**Comment by nick-groupe-ratte** [comment]
Hello @evanjamesjackson The yaml file is already in my first message :)
